[package]
name = "drencher"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]

[dependencies]
rand = "0.3"
docopt = "0.6"
rustc-serialize = "*"
term-painter = "0.2"
time = "0.1"
rayon = "0.4"
pbr = "0.2"
